#!/usr/bin/env bash
# to Run: ./1-world_wide_web <domain> <subdomain>

get_domain_info() {
    local subdomain="${1}"
    local domain="${2}"
    local record_type
    local destination

    record_type="$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
    destination="$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="${1}"

if [[ $# -eq 1 ]]; then
    get_domain_info "www" "${domain}"
    get_domain_info "lb-01" "${domain}"
    get_domain_info "web-01" "${domain}"
    get_domain_info "web-02" "${domain}"
elif [[ $# -eq 2 ]]; then
    subdomain="${2}"
    get_domain_info "${subdomain}" "${domain}"
fi
