#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# show a simple hello world on the server.
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo service nginx restart
