#!/usr/bin/env bash
# Configuring load balancer with haproxy.

apt-get update
apt-get install -y haproxy

echo "frontend http-in
        bind *:80
        mode http
        default_backend servers

frontend load_balancer
        bind *:80
        mode http
        option httpclose
        option forwardfor
        default_backend servers

backend servers
        balance roundrobin
        server 454157-web-01 54.237.84.15:80 check
        server 454157-web-02 3.89.155.134:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
