#!/usr/bin/env bash
# make nginx listen on port 80 again but with short and sweet sol
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
